export interface ClientI {
    id?: number; // Optional: Unique identifier for the client (primary key in database)
    first_name: string // Required: Client's first name
    last_name: string // Required: Client's last name
    address: string // Required: Client's address (e.g., street, city, postal code)
    phone: string // Required: Client's phone number (can be used for contact)
    email: string // Required: Client's email address (for communication purposes)
}
//id?: The id field is optional (?), meaning that it may or may not be provided when creating a new client. Typically, the id is generated by the backend when creating the client.
//first_name, last_name, address, phone, email: These are required fields, representing a client’s personal and contact information.