export interface EmployeeI {
    id?: number; // Optional: Unique identifier for the employee (primary key in database)
    first_name: string; // Required: Employee's first name
    last_name: string; // Required: Employee's last name
    position: string; // Required: Job position or title of the employee (e.g., Manager, Clerk)
}

//id?: The id field is optional (?), meaning that it may or may not be provided when creating a new employee. Typically, the id is generated by the backend when the employee is added.
//first_name, last_name, position: These are required fields, representing the employee's personal and job-related information.