export interface LoanI {
    id?: number; // Optional: Unique identifier for the loan (primary key in database)
    amount: number; // Required: The total amount of money loaned
    interest_rate: number; // Required: The interest rate applied to the loan
    disbursement_date: Date; // Required: The date the loan was disbursed (given to the client)
    due_date: Date; // Required: The date by which the loan must be repaid
    employee: number; // Required: ID of the employee who processed or managed the loan (foreign key)
    status: string; // Required: Current status of the loan (e.g., "active", "paid", "delinquent")
    loan_type: number; // Required: ID for the type of loan (foreign key referencing loan type)
    client: number; // Required: ID of the client who received the loan (foreign key)
}
//id?: The id field is optional (?), meaning that it may or may not be provided when creating a new loan. The id will typically be generated by the backend.
//amount: This represents the total value of the loan given to the client.
//interest_rate: The percentage rate that applies to the loan amount for calculating interest.
//disbursement_date and due_date: These represent the start and end dates of the loan. The loan must be repaid by the due_date.
//employee: This is a reference to the Employee who processed or authorized the loan, represented as an employee ID (foreign key).
//status: A string indicating the current status of the loan, such as "active", "paid", or "delinquent".
//loan_type: Represents the type of loan (e.g., personal loan, mortgage loan) and is a foreign key referring to the LoanType entity.
//client: Represents the client receiving the loan and is a foreign key referring to the Client entity.